// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/page/:slug": {
    params: {
      "slug": string;
    };
  };
  "/robots.txt": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sitemap.xml" | "/blog/:slug" | "/page/:slug" | "/robots.txt" | "/_image/*" | "/*";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[blog].$slug._index.tsx": {
    id: "routes/[blog].$slug._index";
    page: "/blog/:slug";
  };
  "routes/[page].$slug._index.tsx": {
    id: "routes/[page].$slug._index";
    page: "/page/:slug";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};